FROM jtgans/picluster-cross:latest

RUN apk update && \
apk upgrade && \
apk add bash && \
rm -rf /var/cache/apk/*

COPY squidbot-brain-rpi /usr/bin/squidbot-brain

ENTRYPOINT [ "/usr/bin/squidbot-brain" ]
CMD [ "--help" ]

