---
apiVersion: v1
kind: ReplicationController
metadata:
  name: squidbot-brain
  labels:
    version: v2
spec:
  replicas: 1
  selector:
    version: v2
  template:
    metadata:
      labels:
        version: v2
    spec:
      containers:
        - name: squidbot-brain
          image: jtgans/squidbot-brain-rpi:v2
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          ports:
            - name: grpc
              containerPort: 8888
              hostPort: 8888
          args:
            - --port=8888
      restartPolicy: Always
